name: Test

on: [push, pull_request]

jobs:
  node-tests:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Checksum
      run: sh .github/checksum.sh /tmp/checksums.txt
    - name: Setup environment variables
      run: |
        echo "export ACTION_NODE_VERSION=\$(node --version | grep -oE 'v[0-9]+')" >> "$BASH_ENV"
        source $BASH_ENV
    - name: Log out node.js version
      run: |
        node --version
        echo "ACTION_NODE_VERSION=${ACTION_NODE_VERSION}"
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules
          ./package-lock.json
          packages/opentelemetry-api/node_modules
          packages/opentelemetry-context-async-hooks/node_modules
          packages/opentelemetry-context-base/node_modules
          packages/opentelemetry-context-zone/node_modules
          packages/opentelemetry-context-zone-peer-dep/node_modules
          packages/opentelemetry-core/node_modules
          packages/opentelemetry-exporter-jaeger/node_modules
          packages/opentelemetry-exporter-prometheus/node_modules
          packages/opentelemetry-exporter-zipkin/node_modules
          packages/opentelemetry-metrics/node_modules
          packages/opentelemetry-node/node_modules
          packages/opentelemetry-shim-opentracing/node_modules
          packages/opentelemetry-tracing/node_modules
          packages/opentelemetry-web/node_modules
        key: npm-cache-01-{{ matrix.node-version }}-{{ checksum "/tmp/checksums.txt" }}-20B74F85
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          packages/opentelemetry-plugin-grpc/node_modules
          packages/opentelemetry-plugin-http/node_modules
          packages/opentelemetry-plugin-https/node_modules
          packages/opentelemetry-exporter-collector/node_modules
          packages/opentelemetry-plugin-xml-http-request/node_modules
          packages/opentelemetry-resource-detector-aws/node_modules
          packages/opentelemetry-resource-detector-gcp/node_modules
          packages/opentelemetry-resources/node_modules
        key: npm-cache-02-{{ matrix.node-version }}-{{ checksum "/tmp/checksums.txt" }}-20B74F85
    - name: Install Root Dependencies
      run: npm install --ignore-scripts
    - name: Boostrap dependencies
      run: npx lerna bootstrap --no-ci
    - name: Unit tests
      run: npm run test
    - name: Report coverage
      run: if [ "${ACTION_NODE_VERSION}" = "v12" ]; then npm run codecov; fi